### ISSUE TITLE
complete the initial test assignment

### ISSUE THREAD

**Issue by alexanderpanchenko** [suhasbhairav/JuliaMachineLearning#2]

**Comment by alexanderpanchenko** [comment]
format of the header

**Comment by suhasbhairav** [comment]
The header has been formatted and the updated script has been committed on github. The result file for the 20 words including python, perl, etc has been uploaded here on github. The result was generated using the trained model of 1GB corpus( present on dropbox ).

**Comment by alexanderpanchenko** [comment]
1. for future: please include reference when speaking to the files here so there is not ambiguity. 
2. sort the file not only by first column (word) but at the same time by first column first and then by sense id. you can do it with the `sort` unix command. smth like sort -k 1 ... -k 3 ...

**Comment by suhasbhairav** [comment]
I have a question here. When I sort, should the file contain something similar to this:
bank deposit 1 0.50
bank citi 1 0.51
cat mouse 1 0.64
bank river 2 0.78
cat film 2 0.23

OR

should it be:

bank deposit 1 0.50
bank citi 1 0.51
bank river 2 0.78
cat mouse 1 0.64
cat film 2 0.23

**Comment by alexanderpanchenko** [comment]
the first version

**Comment by suhasbhairav** [comment]
The result file has been sorted and the name of the file is testresult_3_1.csv (It is uploaded on github).

**Comment by alexanderpanchenko** [comment]
for future mind that you can upload references to files here (hyperlinks)

**Comment by alexanderpanchenko** [comment]
i checked the result and it seems to be not really good (probably not your fault). however to understand why the results are not good (check words python and jaguar), specify here once again: 
1. which training corpus you used.
2. which code you use to generate the file (GenerateSemantics.jl?)
3. why each sense has different number of neighbours, not 20 or 50 per word per sense? 

bad result : jaguar senses are mixed!

```
jaguar  323i       1  0.86078775
jaguar  buccaneer  1  0.64980966
jaguar  cosworth   1  0.881365
jaguar  creature   1  0.7538807
jaguar  dodge      1  0.87239784
jaguar  dragon     1  0.73619044
jaguar  falcon     1  0.6660185
jaguar  ford       1  0.90041465
jaguar  gladiator  1  0.6407075
jaguar  gloster    1  0.64531446
jaguar  gt40       1  0.8588323
jaguar  gti        1  0.870361
jaguar  harrier    1  0.66113305
jaguar  honda      1  0.87684184
jaguar  hyena      1  0.7389778
jaguar  insectoid  1  0.7507055
jaguar  j2f        1  0.6851529
jaguar  lion       1  0.8240007
jaguar  lockheed   1  0.6521962
jaguar  marauder   1  0.698431
jaguar  mirage     1  0.64910907
jaguar  panther    1  0.673882
jaguar  puma       1  0.73906446
jaguar  reptilian  1  0.7406352
jaguar  roadster   1  0.86242265
jaguar  rover      1  0.8737197
jaguar  sepecat    1  0.7537711
jaguar  skyhawk    1  0.6905357
jaguar  sunbeam    1  0.8765205
jaguar  tentacled  1  0.745793
jaguar  vw         1  0.8669513
jaguar  vx         1  0.64485407
jaguar  winged     1  0.755113
jaguar  xj6        1  0.6428031
jaguar  zoras      1  0.7337678
jaguar  bomber     2  0.64761746
jaguar  chassis    2  0.87858677
jaguar  citroen    2  0.8592557
jaguar  eagle      2  0.7573419
jaguar  falcon     2  0.7489774
jaguar  feline     2  0.76448756
jaguar  gryphon    2  0.74373966
jaguar  holden     2  0.87454903
jaguar  mazda      2  0.8687763
jaguar  monstrous  2  0.73747224
jaguar  owl        2  0.74215585
jaguar  puma       2  0.6456611
jaguar  renault    2  0.8642835
jaguar  serpent    2  0.7452634
jaguar  venom      2  0.7247522
jaguar  crusader   3  0.66485345
jaguar  giant      3  0.77259994
jaguar  gt         3  0.87840205
jaguar  hawk       3  0.66445416
jaguar  mg         3  0.87943447
jaguar  sport      3  0.86529833
jaguar  tornado    3  0.64658284
jaguar  beast      4  0.7468297
jaguar  bmw        4  0.8798755
jaguar  snake      4  0.7463614
```

python senses are mixed

```
python  actionscript  1  0.88700175
python  api           1  0.87945586
python  bindings      1  0.8972165
python  bytecode      1  0.8737606
python  caiman        1  0.75619483
python  cartoons      1  0.547944
python  coldfusion    1  0.88844144
python  compiler      1  0.8870776
python  compilers     1  0.87417775
python  crocodile     1  0.74710625
python  featurette    1  0.57119817
python  horned        1  0.73841697
python  jackal        1  0.7187089
python  javascript    1  0.8981713
python  leopard       1  0.7493601
python  lisp          1  0.8820889
python  lua           1  0.92078596
python  magoo         1  0.59078217
python  mongoose      1  0.7204535
python  monty         1  0.82676554
python  muppet        1  0.57743365
python  opossum       1  0.73236084
python  perl          1  0.963531
python  pheasant      1  0.7311648
python  porcupine     1  0.7201958
python  scripting     1  0.9073298
python  smalltalk     1  0.92175865
python  spamalot      1  0.6888363
python  spectacled    1  0.7845683
python  spoofs        1  0.5517615
python  squirrel      1  0.74715966
python  tcl           1  0.9143377
python  tortoise      1  0.71831715
python  tunes         1  0.5669714
python  unicornis     1  0.7738773
python  vbscript      1  0.88181305
python  zebra         1  0.7285749
python  zorro         1  0.54508185
python  circus        2  0.705449
python  elephant      2  0.7329709
python  falcon        2  0.7188271
python  giant         2  0.7584756
python  goon          2  0.5877628
python  goons         2  0.54751813
python  mole          2  0.7359025
python  php           2  0.9427985
python  ruby          2  0.9209487
python  shorts        2  0.5625763
python  silly         2  0.5412111
python  snoopy        2  0.5751824
python  disney        3  0.56865895
python  scream        3  0.54359245
python  apocalypse    4  0.5609031
python  java          4  0.9325269
python  net           4  0.88353175
python  programming   4  0.89583385
python  python        4  0.62203336
python  cat           5  0.7366104
python  classic       5  0.56335
python  snake         5  0.76386505
```

**Comment by suhasbhairav** [comment]
Training Model: 5 GB Wacky Corpus
Script: GenerateSemantics.jl
I'm getting peculiar results for each sense id for just python as an input. I'll keep you updated on this. I'm trying various combinations to see whether I need to modify GenerateSemantics.jl code or AdaGram generates results in this manner.

**Comment by alexanderpanchenko** [comment]
1. re-run the GenerateSemantics.jl file for these words: python, ruby, jaguar, bank, apple, canon, brother, perl. use 5 senses for each word. generate 20 nearest neighbours for each sense. 
2. upload the file with the result.

**Comment by suhasbhairav** [comment]
I ran a test for just the word "python" in the input file with a sense-id of 1 (hard-coded in GenerateSemantics.jl). The nearest neighbors of not just 1 but also other numbers were generated. I changed the sense-id to 2 in the script and re-ran it. A different set of results with different sense-ids for python were generated. I checked https://github.com/sbos/AdaGram.jl website to see any similar results are present for the example given by them in their description. We can notice that even in their example, results with different sense-ids are being being generated. (For apple, with a sense-id of 1, we can see cherry as its result which has a sense-id of 2). I believe we will have to look deeper into the AdaGram code to understand why the same sense-id result are not being obtained.

**Comment by alexanderpanchenko** [comment]
this is strange, please attach here the results you mention

**Comment by suhasbhairav** [comment]
When I hard-coded the sense-id as 1, I got the following result for python:

 Word    Similar_Word    Sense_id    Semantic_Similarity
  python  monty   1   0.82676554
  python  circus  2   0.705449
  python  spamalot    1   0.6888363
  python  python  4   0.62203336
  python  magoo   1   0.59078217
  python  goon    2   0.5877628
  python  muppet  1   0.57743365
  python  snoopy  2   0.5751824
  python  featurette  1   0.57119817
  python  disney  3   0.56865895
  python  tunes   1   0.5669714
  python  classic 5   0.56335
  python  shorts  2   0.5625763
  python  apocalypse  4   0.5609031
  python  spoofs  1   0.5517615
  python  cartoons    1   0.547944
  python  goons   2   0.54751813
  python  zorro   1   0.54508185
  python  scream  3   0.54359245
  python  silly   2   0.5412111
  python  damned  2   0.5386771
  python  hound   1   0.5378207
  python  terrytoons  1   0.5345945
  python  mickey  2   0.53423274
  python  gilliam 1   0.53375655
  python  caddyshack  1   0.53284425
  python  sketches    1   0.5327364
  python  flintstones 1   0.5324208
  python  mighty  4   0.53237927
  python  mouse   2   0.5304124
  python  muppets 1   0.53000444
  python  idle    2   0.52875674
  python  goolies 1   0.5273988
  python  rutles  1   0.5273717
  python  catdog  1   0.526759
  python  trainspotting   1   0.5266039
  python  incredibles 1   0.5258767
  python  pinocchio   1   0.52492064
  python  goodfellas  1   0.523694
  python  plissken    1   0.5234212
  python  schmo   1   0.5198395
  python  sctv    1   0.5197583
  python  amuck   1   0.5188393
  python  gremlins    1   0.51720643
  python  wicked  3   0.5164097
  python  untouchables    2   0.5160315
  python  parodies    1   0.51524407
  python  cat 1   0.5151613
  python  zombie  2   0.5145425
  python  xanadu  1   0.5143736

For sense-id 2:

Word    Similar_Word    Sense_id    Semantic_Similarity
 python  perl    1   0.963531
 python  php 2   0.9427985
 python  java    4   0.9325269
 python  smalltalk   1   0.92175865
 python  ruby    2   0.9209487
 python  lua 1   0.92078596
 python  tcl 1   0.9143377
 python  scripting   1   0.9073298
 python  javascript  1   0.8981713
 python  bindings    1   0.8972165
 python  programming 4   0.89583385
 python  coldfusion  1   0.88844144
 python  compiler    1   0.8870776
 python  actionscript    1   0.88700175
 python  net 4   0.88353175
 python  lisp    1   0.8820889
 python  vbscript    1   0.88181305
 python  api 1   0.87945586
 python  compilers   1   0.87417775
 python  bytecode    1   0.8737606
 python  gcj 1   0.87300223
 python  apis    1   0.8704994
 python  matlab  1   0.8700731
 python  extensions  1   0.8696916
 python  gtk 1   0.86936206
 python  script  1   0.8690319
 python  applescript 1   0.8678212
 python  rexx    1   0.8662936
 python  debugger    1   0.8653075
 python  haskell 3   0.8647504
 python  ui  2   0.86432767
 python  scripts 1   0.8642422
 python  e4x 1   0.8629726
 python  syntax  1   0.86278903
 python  ocaml   1   0.8625039
 python  native  5   0.86072433
 python  frontend    1   0.86038023
 python  fortran 1   0.85815066
 python  basic   4   0.85807514
 python  mysql   1   0.8573563
 python  ecmascript  1   0.8565386
 python  runtime 1   0.85644
 python  interpreter 1   0.8535849
 python  jvm 1   0.8526745
 python  cli 1   0.85231125
 python  cfml    1   0.8518772
 python  jsp 1   0.85093564
 python  implementation  1   0.8501564
 python  prolog  1   0.8500019
 python  wpf 1   0.84989613

**Comment by alexanderpanchenko** [comment]
write here please call of the function nearest_neighbors with parameter values for these two results

**Comment by alexanderpanchenko** [comment]
This is how to check the number of prototypes!

To examine how many prototypes were learned for a word, use expected_pi function:

julia> expected_pi(vm, dict.word2id["apple"])
30-element Array{Float64,1}:
 0.341832  
 0.658164  
 3.13843e-6 
 2.84892e-7 
 2.58649e-8 
 2.34823e-9 
 2.13192e-10
 1.93554e-11
 1.75725e-12

This function returns a --prototypes-sized array with prior probability of each prototype. As one may see, in this example only first two prototypes have probabilities significantly larger than zero, and thus we may conclude that only two meanings of word "apple" were discovered.

**Comment by alexanderpanchenko** [comment]
share please the 5G model on Dropbox

**Comment by suhasbhairav** [comment]
The call to nearest neighbors:- word = python, vector_model = 5GB Wacky Corpus, sense-id = 2, No of nearest neighbors = 50

 arr = Any[]
     for x in f
         word = strip(string((x)))
         println(word)
         if(haskey(dictionary.word2id,word)==true)

```
         values=nearest_neighbors(vector_model,dictionary,word,2,50)
         if(length(values)>0)
             for y in values
                 empty!(arr)
                 #push!(arr,x)
                 temp_tuple = word,values
                 for z in y
                     push!(arr,string(z))
                 end
                 unshift!(arr,word)
                 write(result_csv,join(arr,"\t"),"\n")
             println(temp_tuple)
             end
         end
```

**Comment by alexanderpanchenko** [comment]
so the calls are actually

for first 

```
nearest_neighbors(vector_model,dictionary,python,1,50)
```

for second

```
nearest_neighbors(vector_model,dictionary,python,2,50)
```

is that correct?

**Comment by suhasbhairav** [comment]
Yes, correct.

**Comment by alexanderpanchenko** [comment]
share the model, i am going to try to reproduce and check myself

**Comment by suhasbhairav** [comment]
https://www.dropbox.com/s/9hi948yhdmhkic3/HugeModel?dl=0
This is the link to the 5GB Wacky Corpus Model.

**Comment by alexanderpanchenko** [comment]
the model is good, smth is wrong with your script most likely

nearest_neighbors(vm, dict, "jaguar", 2, 10)

works for me fine

**Comment by suhasbhairav** [comment]
There seems to be something wrong with my script I believe like you mentioned. I'll have a look at it again.

**Comment by alexanderpanchenko** [comment]
OK

Would be nice if you can fix it by monday meeting.
