### ISSUE TITLE
train a model on  "wacky=wikipedia" corpus

### ISSUE THREAD

**Issue by alexanderpanchenko** [suhasbhairav/JuliaMachineLearning#3]
- use 10-12 threads

**Comment by suhasbhairav** [comment]
The model is being trained currently on the server. It is running on 10 threads.

**Comment by suhasbhairav** [comment]
The model has been trained. It took approximately 12-13 hours to train.

**Comment by alexanderpanchenko** [comment]
great, please generate results (semantically similar words) with the model and attach the file here
- use http://panchenko.me/data/serelex/voc-top-1k.csv + {jaguar, python, bank, brother}
- generate 20 most similar words for each word for each sense

**Comment by alexanderpanchenko** [comment]
great job! you could have used up to 13 threads if this would make things faster

**Comment by suhasbhairav** [comment]
Can I try and see if I can copy the result file(for the 1GB corpus against voc-top-1k+{jaguar,python,bank,brother}) from frink machine onto my laptop to upload it onto github? (If so, is it allowed legally?) I'm not able to figure out any other way of doing so since the content of the result file is somehow not getting copied to the clipboard buffer after executing vim commands for copy.

**Comment by alexanderpanchenko** [comment]
you can copy any files from frink to you laptop

do not commit huge files to github

**Comment by suhasbhairav** [comment]
Should I upload the model generated using 5GB Wacky Corpus to Dropbox?

**Comment by alexanderpanchenko** [comment]
not really needed yet

**Comment by alexanderpanchenko** [comment]
I checked the HugeModel and it is good. Now it is important to train the model on the ukWaC corpus and on the combination of ukWaC + WaCky. Can you launch the learning ASAP so the results are ready by Monday?

**Comment by suhasbhairav** [comment]
So I can go ahead and download the ukwac corpus and train the model on that 12 GB file?

**Comment by suhasbhairav** [comment]
The ukwac 12GB file is being trained at the moment on the server.

**Comment by alexanderpanchenko** [comment]
yes, please. once it finished concatenate ukwac and wacky and train another model 12+5 gb please

**Comment by suhasbhairav** [comment]
Please find the sorted result file of ukwac+wacky:
https://github.com/suhasbhairav/JuliaMachineLearning/blob/master/sort_ukwac_wacky_out.csv

**Comment by alexanderpanchenko** [comment]
these results are good now, thank you!

please make the following modifications:

1) add a column SenseProb with the probability of the given SenseID obtained with the (this should be the THIRD column): 

```
expected_pi(vm, dict.word2id["python"])
5-element Array{Float64,1}:
 0.323456
 0.40748
 0.0725718
 0.196474
 1.84421e-5
```

2)  sort the final files in the following way:

```
sort -k 1,1 -k 2,2n -k 6,6rn sort_ukwac_wacky_out.csv | less
```

3) generate such files for the three models (ukwac, wacky, ukwac+wacky)

**Comment by suhasbhairav** [comment]
https://github.com/suhasbhairav/JuliaMachineLearning/blob/master/sort_ukwac_wacky_combi.csv
https://github.com/suhasbhairav/JuliaMachineLearning/blob/master/sort_ukwacmodel_sense.csv
https://github.com/suhasbhairav/JuliaMachineLearning/blob/master/sort_wacky_sense.csv

**Comment by alexanderpanchenko** [comment]
very good. 

please make just a couple of extra changes:
1. shorten output format  to three digits:  0.11317560909287636 --> 0.113
2. create a header of the file
3. integrate sort into your script (e.g. by calling external command).
4. sort slightly differently:

```
sort -k 1,1 -k 2,2n -k 3,3rn -k 6,6rn sort_ukwac_wacky_out.csv 
```
1. make sure the input script takes as input (1) a CSV file with one word per line (2) number of similar words e.g. 20 and generates the file

**Comment by alexanderpanchenko** [comment]
All scripts should show some help msg on start with no arguments and not: 

```
:~/tmp/adagram/JuliaMachineLearning/src$ julia GenerateSemantics.jl
Warning: could not import Base.add! into NumericExtensions
ERROR: opening file nothing: No such file or directory
 in systemerror at /opt/homebrew-cask/Caskroom/julia/0.3.9/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in open at /opt/homebrew-cask/Caskroom/julia/0.3.9/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in load_model at /Users/alex/.julia/v0.3/AdaGram/src/util.jl:124
 in begin_prg at /Users/alex/tmp/adagram/JuliaMachineLearning/src/GenerateSemantics.jl:30
 in include at /opt/homebrew-cask/Caskroom/julia/0.3.9/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /opt/homebrew-cask/Caskroom/julia/0.3.9/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /opt/homebrew-cask/Caskroom/julia/0.3.9/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/alex/tmp/adagram/JuliaMachineLearning/src/GenerateSemantics.jl, in expression starting on line 63
```
